onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/clk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/reset
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/rom0/mem
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/mem
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/vf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/bf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/df
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/im
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/nmi
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/irq
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rdy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/clk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/ce
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/oe
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/we
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/addr
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rom0/ce
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rom0/oe
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/rom0/addr
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/rom0/d
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/ir
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/ldx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/stxx
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/d
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/ci
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/ni
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/zi
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/c
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/n
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/z
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/o
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/sc
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_inst/d_shift
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/d
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/nn
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/sync
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rw
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/d
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/di
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/do
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/a
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ramcs
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/romcs
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rom0/ce
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/rom0/oe
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/rom0/addr
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/rom0/d
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/clk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/ce
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/pc_reg
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/oe
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/ram0/we
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/addr
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/d
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/reset
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/clk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nmi
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/irq
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rdy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/so
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/di
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/do
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rw
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/ma
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rw_nxt
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/ma_nxt
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sync
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/state
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/flags
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/cres
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/creset
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/ir
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/dil
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/a_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/x_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/y_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/sp_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/pc_reg
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/vf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/bf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/df
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/im
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zf
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cf
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/sr_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/res
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/tmp
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/pc_nxt
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/dout_nxt
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/prev_nmi
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nmi_edge
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/any_int
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_reset
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_reset1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_reset2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_reset3
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_nmi1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_nmi2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_nmi3
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_nmi4
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_nmi5
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_ld_pch
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_exec
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_branch
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_dataFetch
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_update
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_afterWrite
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_ix1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_ix2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_iy1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_iy2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_abs1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_jmpi1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_jsr1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_jsr2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_pul
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rts1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rts2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rts3
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rti1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rti2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_rti3
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/s_sync
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/cond
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/branch
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/taken
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/jmp
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/jmpi
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/php
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/pha
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/psh
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/plp
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/pla
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/pul
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/jsr
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rts
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rti
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/brk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nop
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/inx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/iny
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/dex
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/dey
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/clc
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cld
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/clv
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cli
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sec
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sed
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sei
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/tay
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/tya
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/tax
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/txa
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/tsx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/txs
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ror_a
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/lsr_a
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rol_a
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/asl_a
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ldx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/stxx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ror
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/rol
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/lsr
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/asl
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/inc
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/dec
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ldy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/styy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cmp
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ldy_i
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cpy_i
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ldx_i
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cpx_i
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/mop
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/ix
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zp
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/imm
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/abs
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/iy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zpy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zpx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/absy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/absx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zpxy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/absxy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sta
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/sty
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/stx
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/staxy
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2m
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2x
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp0_us
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp1_us
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/grp2_us
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/axy_reg
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/axy_addo
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/sp_addo
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/firq
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/fbrk
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nfo0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cfo0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/vfo0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zfo0
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nfo1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cfo1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/vfo1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zfo1
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/nfo2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/cfo2
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/zfo2
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp0_o
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp1_o
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/grp2_o
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/vec
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/cpu0/xyz_reg
add wave -noupdate -format Logic -radix hexadecimal /bc6502_tb/cpu0/takb
add wave -noupdate -format Literal -radix hexadecimal /bc6502_tb/ram0/nn
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {595000 ps} 0}
configure wave -namecolwidth 194
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2100 ns}
